import type { Metadata, Viewport } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { SerwistProvider } from "@serwist/turbopack/react";
import "./globals.css";
import "@/lib/fontawesome";
import { Providers } from "@/components/providers";
import { getUser } from "@/lib/supabase/server";
import { getProfile } from "@/lib/supabase/queries";
import { getSiteSettings } from "@/lib/supabase/settings";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-display",
  subsets: ["latin"],
  display: "swap",
  weight: ["700", "800"],
});

export const metadata: Metadata = {
  // Live deployment domain — makes relative og:image URLs resolve to a
  // working address so WhatsApp/social link previews render. Update when a
  // custom domain goes live.
  metadataBase: new URL("https://conectge.netlify.app"),
  title: {
    default: "GEMarket — Compra y vende en Guinea Ecuatorial",
    template: "%s · GEMarket",
  },
  description:
    "El mercado de anuncios clasificados de Guinea Ecuatorial. Publica gratis y contacta directamente por WhatsApp. Vehículos, inmobiliaria, empleo, electrónica y mucho más en Malabo y Bata.",
  keywords: [
    "anuncios Guinea Ecuatorial",
    "comprar vender Malabo",
    "clasificados Bata",
    "OLX Guinea Ecuatorial",
    "mercado online GE",
  ],
  openGraph: {
    type: "website",
    locale: "es_GQ",
    siteName: "GEMarket",
    title: "GEMarket — Compra y vende en Guinea Ecuatorial",
    description:
      "Publica tu anuncio gratis y contacta por WhatsApp. El mercado de Guinea Ecuatorial.",
  },
  // Favicon is auto-generated by Next.js from src/app/icon.png (file-based
  // icon convention) — no manual `icons.icon` field needed here. PWA
  // install icons come from manifest.ts instead (separate from the
  // favicon); apple-touch-icon.png lives in public/ (not a route-segment
  // icon file), so it needs an explicit `icons.apple` entry.
  icons: {
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "GEMarket",
  },
};

export const viewport: Viewport = {
  themeColor: "#2563EB",
  width: "device-width",
  initialScale: 1,
  // Lets standalone-mode content draw under the notch/home-indicator
  // instead of iOS boxing it in behind a flat system bar — paired with the
  // safe-area-inset padding in globals.css and on the fixed bottom sheets,
  // which reserve exactly that same space back so nothing sits under the
  // hardware cutouts. No visual change for regular (non-installed) browser
  // tabs, since the compensating padding cancels it out there too.
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const profile = user ? await getProfile(user.id) : null;
  const settings = await getSiteSettings();

  // Admin-configured brand color (site settings). globals.css maps every
  // bg-primary/text-primary utility to var(--primary), so overriding the one
  // variable retints the whole site. The value is validated as #RRGGBB by
  // saveSiteSettingsAction, and re-checked here before being inlined.
  const primaryColor = /^#[0-9a-fA-F]{6}$/.test(settings.primary_color)
    ? settings.primary_color
    : null;

  return (
    <html lang="es" className={`${inter.variable} ${plusJakarta.variable} h-full antialiased`}>
      <body className="h-full">
        {primaryColor && (
          // Dark mode normally pairs --primary with near-black foreground
          // text; an arbitrary admin color can't guarantee that contrast, so
          // the override standardizes on white text in both themes.
          <style>{`:root, .dark { --primary: ${primaryColor}; --ring: ${primaryColor}; --primary-foreground: #ffffff; }`}</style>
        )}
        <SerwistProvider swUrl="/serwist/sw.js">
          <Providers initialUser={user} initialProfile={profile}>
            {children}
          </Providers>
        </SerwistProvider>
      </body>
    </html>
  );
}
